### ISSUE TITLE
Would it be possible to add background shapes to individual system tray elements?

### ISSUE THREAD

**Issue by ryu-ketsueki** [luisbocanegra/plasma-panel-colorizer#33]
Previously, Psifidotos, maintainer of Latte Dock at the time, created a fork of the system tray that allowed to add background shapes to individual elements in the tray. It was called plasma-systray-latte-tweaks.

I noticed that the Panel Colorizer can already identify and define a color for each of the elements in the tray. Would it be possible to also add a background shape to said elements as option to a background to the entire widget?

Edited by @luisbocanegra

# Tasks
- [x] Detect system tray elements
- [x] Implement shape margin
- [x] Fix incorrect padding

**Comment by luisbocanegra** [comment]
Should be. Will try implementing it for the next version.

**Comment by luisbocanegra** [comment]
Made some progress on this, can you test by installing from [pre-rewrite branch](https://github.com/luisbocanegra/plasma-panel-colorizer/tree/pre-rewrite) and tell me if different values of spacing (*Layout* > *Spacing*) look correct?

![Screenshot_20240807_153635](https://github.com/user-attachments/assets/3011cdde-8da7-4bc1-a37e-ede39d4c75de)

  Still need to add vertical spacing between rows here without making the two rows still fill the height of a regular widget:

  ![Screenshot_20240807_155253](https://github.com/user-attachments/assets/8d403327-f043-4a36-bb12-68fb32dffed4)

And the unreleased background blur will have to work there too 🤯

Other things like detecting when a tray icon is added/removed don't work yet, or making the text "follow" the color of the background

Overall I will probably do a rewrite first so this will take some time to be in a usable state to be shipped.

**While the widget may seem to work fine in the current state I recommend you switch back to the latest stable after doing these tests**

**Comment by luisbocanegra** [comment]
Done in [rewrite](https://github.com/luisbocanegra/plasma-panel-colorizer/tree/rewrite) branch

![Screenshot_20240918_110434](https://github.com/user-attachments/assets/21cd6bfe-3a64-4df1-b7ae-7c6812bf7163)

Will be available when the rewrite is finished and stable https://github.com/luisbocanegra/plasma-panel-colorizer/issues/69
