### ISSUE TITLE
Project rewrite (Work in progress, needs testing)

### ISSUE THREAD

**Issue by luisbocanegra** [luisbocanegra/plasma-panel-colorizer#69]
Tracking the progress of https://github.com/luisbocanegra/plasma-panel-colorizer/pull/66

- [x] Fix lag on Plasma startup
- [x] Use Kirigami.ShadowedRectangle for backgrounds
- [x] Fix panel freezing
- [x] Find Panel Background
- [x] Find widgets
- [x] Monitor for count change
- [x] Background shapes for individual tray elements https://github.com/luisbocanegra/plasma-panel-colorizer/issues/33
- [x] Unify color selection component https://github.com/luisbocanegra/plasma-panel-colorizer/issues/40
  - [x] New color component logic
- [x] Control margin on four axis instead of just horizontal and vertical (anchors and Layout attached properties) https://github.com/luisbocanegra/plasma-panel-colorizer/issues/57
  - [x] Fix margin configuration for vertical panels
- [x] https://github.com/luisbocanegra/plasma-panel-colorizer/issues/70
  - [x] Get and pass widget name to background areas
  - [x] https://github.com/luisbocanegra/plasma-panel-colorizer/issues/65
- New colorization logic
  - [x] Re-implement background colorization
  - [x] Re-implement foreground colorization
    - [x] Bring back "Force Icon color"
  - [x] Custom color
  - [x] System color scheme
  - [x] Custom color list
  - [x] Follow background (panel, widget, system tray item)
- [x] Update and move existing options into new Tabs
- Maybe port existing config files to new format
- [x] Reload tray area and possibly others when switching panel vertical
- [x] Fix tray area breaking with some Plasmoid/StatusNotifier (reproducible with NeoChat)
- [x] Don't auto-load presets when globally disabled

**Comment by luisbocanegra** [comment]
Getting there, static custom/system color should fully now.

![Screenshot_20240915_131603](https://github.com/user-attachments/assets/47ac3189-a975-4d77-a689-aa3e2d62b733)

**Comment by luisbocanegra** [comment]
Per widget override mostly done

![Screenshot_20240921_130309](https://github.com/user-attachments/assets/dcefcbbc-f155-432d-9213-0f6978ec2825)

**Comment by luisbocanegra** [comment]
Let's merge now, will do the blur in a separate PR

**Comment by nikoraasu** [comment]
I found the time to finally test this, as I really care about this project.
So, the new UI is a little more complex to understand at first, but overall the new options are great, and after playing around I got the hang of everything.

So for the unified backgrounds. It might be a me, but I would say it's a little confusing. 
I had to mess around with it a lot before I understood how it works. I think changing the "start/end" values to something like "Connect to Right/Connect to Left" would make much more sense, as right now I thought I have to put both start and end on two widgets that I wanted to connect, only to realize later that I only had to put "End" on the right most widget that I wanted connected to the one that's on the left.

Also something with unified backgrounds that I think would be great if fixed (though not sure if it's even possible as  that might just be how plasma widgets work), is the fact that they offset the widgets around them. What I mean by that, is when I connected these two widgets together 
![image](https://github.com/user-attachments/assets/b55e4a70-3b25-4675-8353-f6d93660aa42)
I noticed that my clock that is supposed to be centered got offset by like 5 pixels to the left. Noticeable? Probably not, still quite annoying though. I could probably make an override for that but I feel like having to mess around with overrides just to move stuff by pixels every time something is offset by connections is pretty janky. 

Adding spacing (including negative spacing, quite sure it'd be impossible to implement though) to overrides would also be pretty useful as right now some of the connected widgets look goofy with them being so far away, and I would like them to be a little closer together (have not yet found a way to do that for just specific widgets, maybe there is a way that I have missed though, let me know!). 

Also might be an issue on my side, but the widget is still visible in the panel despite having the option for it to disappear checked.

Overall I think this is a good direction for the widget and many of the options improved customizability of KDE Plasma by a huge huge margin. 

Also, I hope my feedback does not come out as demands. I am a developer too and I understand that some things may not be possible to implement or way harder to do than end users think, so that is completely understandable to me.

**Comment by luisbocanegra** [comment]
> I found the time to finally test this, as I really care about this project. So, the new UI is a little more complex to understand at first, but overall the new options are great, and after playing around I got the hang of everything.

Yeah, it's also a bit heavier now (both visually and in code), specially the Appearance tab but I wanted to make it faster to configure things without having to switch between tab/apply/tab too much. The good thing is they all are basically the same component so only a single file needs to be changed most of the time, any suggestions on how to make the layout easier to use are appreciated.

> So for the unified backgrounds. It might be a me, but I would say it's a little confusing. I had to mess around with it a lot before I understood how it works. I think changing the "start/end" values to something like "Connect to Right/Connect to Left" would make much more sense, as right now I thought I have to put both start and end on two widgets that I wanted to connect, only to realize later that I only had to put "End" on the right most widget that I wanted connected to the one that's on the left.

Yeah I was thinking of making it so that when one of the "End" was checked it automatically grayed(disabled) out everything in between start and end, but I also think there must be a better UI/UX to implement this.

Initially I had four states `[disabled, start, middle, end] and each widget was assigned a state with disabled being the default all from the settings, while this had a more involved configuration it was easier on the code as widgets didn't have to be aware of the state of the other widgets.

But later I changed it so there is an extra variable that defines `[default, start, end]`, which are exposed to the configuration, less manual configuration but also somewhat buggier as it relies on all widgets refreshing an array of states so the `default` ones know whether or not they need to be in `middle` or `disabled` state. https://github.com/luisbocanegra/plasma-panel-colorizer/commit/be7ce3ad96fffa9cd1a1538269880257254d96d1 maybe I can go to the previous approach while also making the UI be the one setting the four states with a simpler interface, any suggestions you may have on this are appreciated.

> Also something with unified backgrounds that I think would be great if fixed (though not sure if it's even possible as that might just be how plasma widgets work), is the fact that they offset the widgets around them. What I mean by that, is when I connected these two widgets together ![image](https://private-user-images.githubusercontent.com/86488693/373885909-b55e4a70-3b25-4675-8353-f6d93660aa42.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxNTM4NjMsIm5iZiI6MTcyODE1MzU2MywicGF0aCI6Ii84NjQ4ODY5My8zNzM4ODU5MDktYjU1ZTRhNzAtM2IyNS00Njc1LTgzNTMtZjZkOTM2NjBhYTQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA1VDE4MzkyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5MGZkYWJiODkwZDFkODhhY2QyOGQ0NDhhOWIyZDZlOTQ3M2UwMTE3Mjc2NzliZjMwMzBhZjhlMGVmNzQzMTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.TAkoacEKPFGocB7_iaxiaLTXLQuTV3M_a9z5tFPQ7eA) I noticed that my clock that is supposed to be centered got offset by like 5 pixels to the left. Noticeable? Probably not, still quite annoying though. I could probably make an override for that but I feel like having to mess around with overrides just to move stuff by pixels every time something is offset by connections is pretty janky.

Hmm, currently all the widgets starting from the second one have an margin on the left, the regular spacing of the [GridLayout](https://doc.qt.io/qt-6/qml-qtquick-layouts-gridlayout.html) is set to 0, which allows me to remove the additional margin at the left of widgets with `middle` and `end` states making them "connect" with the other widgetss visually. It should be possible to avoid things moving around by leaving the space in-between. Will have to experiment with that as respecting the centering is something I didn't test for.

> Adding spacing (including negative spacing, quite sure it'd be impossible to implement though) to overrides would also be pretty useful as right now some of the connected widgets look goofy with them being so far away, and I would like them to be a little closer together (have not yet found a way to do that for just specific widgets, maybe there is a way that I have missed though, let me know!).

I experimented with this for a bit and it seemed possible, if nothing breaks I will expose negative values to the UI.

> Also might be an issue on my side, but the widget is still visible in the panel despite having the option for it to disappear checked.

Yes haven't added that code back as I have been using it for quickly debugging random values but will bring it back once I finish working on some other things.

> Overall I think this is a good direction for the widget and many of the options improved customizability of KDE Plasma by a huge huge margin.

Thanks! I have so many other ideas to try implementing, had to write them down so I don't forget.

> Also, I hope my feedback does not come out as demands. I am a developer too and I understand that some things may not be possible to implement or way harder to do than end users think, so that is completely understandable to me.

It does not, I appreciate constructive, well thought feedback, even if something doesn't seem possible at first glance I like little challenges here an there. 

> EDIT: Forgot, having an automated uninstall of the widget when installed from source would be great, as I want to come back to AUR version of the widget instead of having it built from source.

Yeah, there are some install_manifest.txt files in the build folder you can check and remove the folders manually

```
/usr/lib/qt6/qml/org/kde/plasma/panelcolorizer/
/home/$USER/.local/share/plasma/plasmoids/luisbocanegra.panel.colorizer/
/home/$USER/.local/share/metainfo/luisbocanegra.panel.colorizer.appdata.xml
```

Making a uninstall script should be straight forward.
