### ISSUE TITLE
Preset management

### ISSUE THREAD

**Issue by luisbocanegra** [luisbocanegra/plasma-panel-colorizer#9]
# Preset management
With so many knobs it could be useful to have preset functionality or at least some inbuilt presets to choose from.

- [x] Create from current settings
- [x] List saved presets
  - [x] Apply
  - [x] Update from current settings
  - [x] Delete
- [x] Restore defaults
- [x] Confirmation for create/update/delete actions
- [x] Show last loaded preset 

# TODO
- [x] Save preset name instead of index (breaks if presets are added/removed)

# This is now ready for testing
Install manually and try the following:
- Create as many varied presets as you can
- Test that changing between presets updates properly all the settings tabs and panel appearance
- Resetting to defaults actually resets everything correctly
- Loading / updating / deleting presets works as intended
